---
- name: Install neovim (macOS)
  community.general.homebrew:
    name: neovim
    state: present
    path: "{{ homebrew_brew_bin }}"

- name: Install tree-sitter CLI (macOS)
  community.general.homebrew:
    name: tree-sitter
    state: present
    path: "{{ homebrew_brew_bin }}"
